### ISSUE TITLE
How to have these datalayer values available in the Page View tag?

### ISSUE THREAD

**Issue by robert1112** [RitwikGA/dgTrack#1]
Hi @RitwikGA 

BIG thanks for sharing such awesome solution. It works really awesome and the info is so valuable.

I read 2 of your posts and set up custom dimension in GA too. Anyway, how to have these datalayer value (pageviewCount, Acquisition Source Acquisition Medium Acquisition Campaign Acquisition Landing Page Acquisition Date Acquisition Month)  available in Page View tag?

1. So pageview event will have these data? (Correct?)
2.If I don't have an additional tag triggered on Event Trigger – ‘firstAttribution‘, but have a GA Page view tag with Acquisition Source custom dimensions, will Acquisition Source custom dimension will be recorded in GA if the Acquisition Source is available in data layer? 

I found one trick to push datalayer to page view tag pasted below. But I dont know how to make it work with yours. 

Thank you so much and have a great day.

```
      // Set the data model keys directly so they can be used in the Page View tag
      window.google_tag_manager[{{Container ID}}].dataLayer.set('browsingBehavior', payload);
      
      // Also push to dataLayer
      window.dataLayer.push({
        event: 'custom.navigation',
        browsingBehavior: payload
      });
```

**Comment by RitwikGA** [comment]
Not sure about the data model .set/.get but an easy way to have something populated in pageview event is to declare dataLayer before the gtm tag. (Eg: https://developers.google.com/tag-manager/devguide)

```
dgTrack.utmValues({
 cookie_name: 'lutm',
 cookie_duration: 180,
 attributionType : 'last',
 callback : function(obj){	
 // Insert your event tracking code here : facebook custom event example //
 window.dataLayer = window.dataLayer || [];
 window.dataLayer.push({'source':obj['source']})    
}
})

// add gtm tag here //
```

**Comment by robert1112** [comment]
Hi @RitwikGA  Thank you so much. I will see if i can get it work.  Thank you.
